[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"
  targetPort = 3001
  port = 8888
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
